apiVersion: v1
kind: Pod
metadata:
  name: resource-limitation
  labels:
    project: roboshop
    env: development

spec:
  containers:
  - name: nginx
    image: nginx
    
    resources:
      requests:   # minimum resources required
        memory: "150Mi"
        cpu: "100m"

      limits:     # maximum resources allowed
        memory: "200Mi"
        cpu: "150m"