apiVersion: v1
kind: Pod
metadata:
  name: env-secret
  labels:
    purpose: secret
    env: development
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
     - secretRef:
        name: my-secret-name 